# Exploração e tratamento inicial de dados com Pandas

Este notebook é um roteiro de estudo para os primeiros passos ao receber uma nova base de dados.

A ideia não é apenas executar comandos, mas entender o que cada etapa revela sobre o conjunto de dados e quais decisões podem ser tomadas a partir disso.

Use este material como um checklist inicial para projetos de Data Analytics e Data Engineering.

## Objetivos do notebook

Ao final deste fluxo, você deve conseguir:

- carregar uma base tabular com Pandas;
- inspecionar as primeiras linhas do DataFrame;
- entender dimensões, tipos de dados e estatísticas iniciais;
- identificar valores nulos;
- padronizar nomes de colunas;
- preparar a base para análises e transformações futuras.

Pense neste notebook como a primeira conversa com a base: antes de transformar, você precisa conhecer o terreno.

## Checklist inicial ao receber uma nova base

Antes de sair criando análises, vale passar por algumas perguntas:

- O arquivo foi carregado corretamente?
- Quantas linhas e colunas existem?
- Quais são os nomes das colunas?
- Os tipos de dados fazem sentido?
- Existem valores nulos?
- Existem colunas com nomes difíceis de usar?
- Existem possíveis duplicidades?
- Quais colunas parecem ser chaves, categorias, datas e métricas?

Essas perguntas ajudam a criar um diagnóstico inicial antes de qualquer tratamento mais avançado.

## 1. Preparação do ambiente

Começamos importando o Pandas e conferindo a versão instalada.

In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

2.3.3

## 2. Carregamento da base

Nesta etapa, definimos o caminho do arquivo e carregamos a base em um DataFrame.

Depois da leitura, visualize as primeiras linhas para responder: a base abriu corretamente? As colunas e valores parecem estar no formato esperado?

In [35]:
data = "data/superstore.csv"

df = pd.read_csv(data, encoding="ISO-8859-1")

df.head(5)

,Linha ID,Ordem ID,Data Ordem,Data Envio,Modo Envio,Cliente ID,Nome Cliente,Segmento,PaÃ­s,Cidade,...,Codigo Postal,Regiao,Produto ID,Categoria,Sub-Categoria,Nome Produto,Vendas,Quantidade,Desconto,Lucro
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## 3. Primeiro diagnóstico da base

Agora vamos entender a estrutura geral do DataFrame. Esta etapa é essencial para decidir os próximos tratamentos.

Observe quantidade de registros, nomes das colunas, tipos de dados e presença inicial de valores ausentes.

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Linha ID           9994 non-null   int64
 1   Ordem ID           9994 non-null   object
 2   Data Ordem         9994 non-null   object
 3   Data Envio         9994 non-null   object
 4   Modo Envio         9994 non-null   object
 5   Cliente ID         9994 non-null   object
 6   Nome Cliente       9994 non-null   object
 7   Segmento           9994 non-null   object
 8   PaÃ­s              9994 non-null   object
 9   Cidade             9994 non-null   object
 10  Estado             9994 non-null   object
 11  Codigo Postal      9994 non-null   int64
 12  Regiao             9994 non-null   object
 13  Produto ID         9994 non-null   object
 14  Categoria          9994 non-null   object
 15  Sub-Categoria      9994 non-null   object
 16  Nome Produto       9994 non-null   object
 17  Vendas             9994 non-null   float64
 18  Quantidade         9994 non-null   int64
 19  Desconto           9994 non-null   float64
 20  Lucro              9994 non-null   float64
 21  desconto_aplicado  9994 non-null   bool
 22  lucro_por_unidade  9994 non-null   float64
 23  categoria_lucro    9994 non-null   object
 24  margem_lucro       9994 non-null   float64
 25  nivel_vendas       9994 non-null   object
 26  desconto_elevado   9994 non-null   bool
dtypes: bool(2), float64(5), int64(3), object(17)
memory usage: 1.9+ MB

In [36]:
df.columns

Index(['Linha ID', 'Ordem ID', 'Data Ordem', 'Data Envio', 'Modo Envio',
       'Cliente ID', 'Nome Cliente', 'Segmento', 'PaÃ­s', 'Cidade', 'Estado',
       'Codigo Postal', 'Regiao', 'Produto ID', 'Categoria', 'Sub-Categoria',
       'Nome Produto', 'Vendas', 'Quantidade', 'Desconto', 'Lucro'],
      dtype='object')

In [37]:
df.dtypes

Linha ID           int64
Ordem ID          object
Data Ordem        object
Data Envio        object
Modo Envio        object
Cliente ID        object
Nome Cliente      object
Segmento          object
PaÃ­s             object
Cidade            object
Estado            object
Codigo Postal      int64
Regiao            object
Produto ID        object
Categoria         object
Sub-Categoria     object
Nome Produto      object
Vendas           float64
Quantidade         int64
Desconto         float64
Lucro            float64
dtype: object

## 4. Estatísticas descritivas

As estatísticas descritivas ajudam a identificar escala, distribuição e possíveis valores estranhos nas colunas numéricas.

Nesta leitura, procure valores mínimos ou máximos inesperados, médias muito distantes da mediana e colunas que merecem investigação.

In [32]:
df.describe()

,Linha ID,Codigo Postal,Vendas,Quantidade,Desconto,Lucro,lucro_por_unidade,margem_lucro
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896,7.799372,12.031393
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108,56.074974,46.675435
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000,-1319.995600,-275.000000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750,0.722800,7.500000
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500,2.767000,27.000000
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000,8.703200,36.250000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000,1679.995200,50.000000

## 5. Tratamentos iniciais

Depois do diagnóstico, começamos os tratamentos mais comuns em uma base nova.

Aqui o foco é preparar o DataFrame para ficar mais fácil, consistente e seguro de analisar.

#### Verificar se existem dados nulos nas colunas

Nesta etapa, investigue a qualidade dos dados antes de criar novas análises.

Pense nas seguintes perguntas:

- Existe alguma coluna com valores ausentes?
- Quantos valores nulos existem em cada coluna?
- Alguma coluna importante para análise, como vendas, lucro, quantidade, desconto ou região, possui dados faltantes?
- Se existirem valores nulos, faz mais sentido remover, preencher ou apenas registrar essa informação?

Objetivo da célula de código abaixo: gerar uma visão simples da quantidade de valores nulos por coluna.

#### Renomear as colunas

Nesta etapa, padronize os nomes das colunas para facilitar o uso durante o projeto.

Antes de renomear, observe os nomes atuais das colunas e defina um padrão. Uma boa prática é usar nomes em minúsculo, sem espaços e sem acentos, por exemplo: `data_pedido`, `regiao`, `vendas`, `lucro`.

Pense nas seguintes perguntas:

- Os nomes atuais estão claros?
- Existem espaços, acentos ou letras maiúsculas que podem atrapalhar o acesso às colunas?
- Qual padrão será usado em todo o notebook?
- Depois de renomear, como você pode conferir se a mudança foi aplicada corretamente?

Objetivo da célula de código abaixo: criar um mapeamento dos nomes antigos para os novos nomes e aplicar esse padrão ao DataFrame.

#### Verificar possíveis registros duplicados

Duplicidades podem distorcer contagens, somas, médias e indicadores. Antes de remover qualquer coisa, investigue se uma linha repetida representa erro ou se pode ser uma ocorrência válida no contexto da base.

Pense nas seguintes perguntas:

- Existe alguma linha completamente duplicada?
- Existe alguma coluna que deveria funcionar como identificador único?
- Uma duplicidade deve ser removida ou apenas registrada como ponto de atenção?

Objetivo da próxima célula de estudo: medir se existem duplicidades e decidir como tratá-las.

#### Revisar tipos de dados

Depois de olhar os tipos com `df.dtypes` e `df.info()`, avalie se cada coluna foi interpretada corretamente pelo Pandas.

Pense nas seguintes perguntas:

- Colunas de data foram carregadas como data ou como texto?
- Colunas numéricas foram carregadas como número?
- Colunas categóricas fazem sentido como texto/categoria?
- Alguma conversão de tipo precisa ser feita antes das análises?

Objetivo da próxima célula de estudo: listar possíveis conversões necessárias e aplicar somente as que fizerem sentido.

## 6. Recortes para análise

Com a base mais conhecida e padronizada, podemos criar subconjuntos para responder perguntas específicas.

Nesta parte, o notebook começa a sair do diagnóstico geral e entrar em análises orientadas por perguntas.

#### Dividindo o DF em dois subconjuntos por região

In [7]:
df_west = df[df['Regiao'] == 'West']
df_south = df[df['Regiao'] == 'South']

In [8]:
sales_west = df_west['Vendas'].sum()
sales_south = df_south['Vendas'].sum()

In [9]:
sales_west

725457.8245

In [10]:
sales_west

725457.8245

## 7. Criação de novas variáveis

Criar novas colunas é uma forma de transformar dados brutos em informação mais útil para análise.

Sempre que criar uma variável, tente explicar qual pergunta ela ajuda a responder.

#### Criando uma nova coluna indicando se houve desconto

In [11]:
df['desconto_aplicado'] = df['Desconto'] > 0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Linha ID           9994 non-null   int64
 1   Ordem ID           9994 non-null   object
 2   Data Ordem         9994 non-null   object
 3   Data Envio         9994 non-null   object
 4   Modo Envio         9994 non-null   object
 5   Cliente ID         9994 non-null   object
 6   Nome Cliente       9994 non-null   object
 7   Segmento           9994 non-null   object
 8   PaÃ­s              9994 non-null   object
 9   Cidade             9994 non-null   object
 10  Estado             9994 non-null   object
 11  Codigo Postal      9994 non-null   int64
 12  Regiao             9994 non-null   object
 13  Produto ID         9994 non-null   object
 14  Categoria          9994 non-null   object
 15  Sub-Categoria      9994 non-null   object
 16  Nome Produto       9994 non-null   object
 17  Vendas             9994 non-null   float64
 18  Quantidade         9994 non-null   int64
 19  Desconto           9994 non-null   float64
 20  Lucro              9994 non-null   float64
 21  desconto_aplicado  9994 non-null   bool
 22  lucro_por_unidade  9994 non-null   float64
dtypes: bool(1), float64(4), int64(3), object(15)
memory usage: 1.7+ MB

#### Criando uma nova coluna de "Lucro por Unidade" Formula: (Lucro / Quantidade)

In [13]:
df['lucro_por_unidade'] = df['Lucro'] / df['Quantidade']

In [15]:
df[['Lucro', 'Quantidade', 'lucro_por_unidade', 'desconto_aplicado']].head()

      Lucro  Quantidade  lucro_por_unidade  desconto_aplicado
0   41.9136           2            20.9568              False
1  219.5820           3            73.1940              False
2    6.8714           2             3.4357              False
3 -383.0310           5           -76.6062               True
4    2.5164           2             1.2582               True

#### Criando função para categorizar o lucro

In [17]:
def categorizar_lucro(lucro):
    if lucro > 50:
        return 'Margem Alta'
    elif lucro > 0:
        return 'Margem Média'
    else:
        return 'Margem Negativa'

In [18]:
df['categoria_lucro'] = df['Lucro'].apply(categorizar_lucro)

In [20]:
df[['Lucro', 'Quantidade', 'lucro_por_unidade', 'categoria_lucro']].head()

      Lucro  Quantidade  lucro_por_unidade  categoria_lucro
0   41.9136           2            20.9568     Margem Média
1  219.5820           3            73.1940      Margem Alta
2    6.8714           2             3.4357     Margem Média
3 -383.0310           5           -76.6062  Margem Negativa
4    2.5164           2             1.2582     Margem Média

#### Calculando a margem de Lucro como porcentagem %

In [23]:
df['margem_lucro'] = df.apply(lambda x: (x['Lucro'] / x['Vendas']) * 100, axis=1)

In [25]:
df[['Lucro', 'Quantidade', 'lucro_por_unidade', 'categoria_lucro', 'margem_lucro']].head()

      Lucro  Quantidade  lucro_por_unidade  categoria_lucro  margem_lucro
0   41.9136           2            20.9568     Margem Média         16.00
1  219.5820           3            73.1940      Margem Alta         30.00
2    6.8714           2             3.4357     Margem Média         47.00
3 -383.0310           5           -76.6062  Margem Negativa        -40.00
4    2.5164           2             1.2582     Margem Média         11.25

In [26]:
df['nivel_vendas'] = df['Vendas'].apply(lambda x: 'Alta' if x > 500 else 'Baixa')

In [27]:
df[['Lucro', 'Quantidade', 'lucro_por_unidade', 'categoria_lucro', 'margem_lucro', 'nivel_vendas']].head()

,Lucro,Quantidade,lucro_por_unidade,categoria_lucro,margem_lucro,nivel_vendas
0,41.9136,2,20.9568,Margem Média,16.00,Baixa
1,219.5820,3,73.1940,Margem Alta,30.00,Alta
2,6.8714,2,3.4357,Margem Média,47.00,Baixa
3,-383.0310,5,-76.6062,Margem Negativa,-40.00,Alta
4,2.5164,2,1.2582,Margem Média,11.25,Baixa

In [28]:
df['desconto_elevado'] = df['Desconto'].apply(lambda x: True if x > 0.2 else False)

In [29]:
df[['Lucro', 'Quantidade', 'lucro_por_unidade', 'categoria_lucro', 'margem_lucro', 'nivel_vendas', 'desconto_elevado']].head()

,Lucro,Quantidade,lucro_por_unidade,categoria_lucro,margem_lucro,nivel_vendas,desconto_elevado
0,41.9136,2,20.9568,Margem Média,16.00,Baixa,False
1,219.5820,3,73.1940,Margem Alta,30.00,Alta,False
2,6.8714,2,3.4357,Margem Média,47.00,Baixa,False
3,-383.0310,5,-76.6062,Margem Negativa,-40.00,Alta,True
4,2.5164,2,1.2582,Margem Média,11.25,Baixa,False